import React, { useEffect, useRef, useState } from 'react';

export function Projects() {
  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef(null);

  const projects = [
    {
      title: "Machine Learning for Weather Prediction",
      description: "Jupyter notebooks that examine two European cities based on 10-year weather data to predict and assess the accuracy of 1-day and 7-day weather forecasts using machine learning methods (FFNN/LSTM/Random Forest).",
      tags: ["Python", "Machine Learning", "Data Science"],
      github: "https://github.com/sebastian-shirazi/AI-Driven-Risk-Assessment-for-Basketball",
    },
    {
      title: "Hoos Hooping",
      description: "Mobile application aimed to bring university students together to arrange pickup basketball games through creating games in the app, inviting their friends to games, and having chat and maps functionality for games.",
      tags: ["React Native", "Node.js", "MySQL"],
      github: "https://github.com/sebastian-shirazi/HoosHooping",
    },
    {
      title: "AI Powered Risk Assessment Tool",
      description: "Uses AI to analyze video footage of basketball players to assess their risk of injury based on their movement patterns, considering factors such as fatigue, differentiation from proper form, and position of key joints.",
      tags: ["Python", "Computer Vision", "AI"],
      github: "https://github.com/sebastian-shirazi/AI-Driven-Risk-Assessment-for-Basketball",
    },
    {
      title: "Event Management App",
      description: "Full stack web application for managing events, with functionality for logging in via Google OAuth, creating events, RSVPing to events, leaving messages on events, and attaching files to events. Admin accounts can also be created and have elevated functionality.",
      tags: ["Django", "Bootstrap", "AWS S3"],
      github: "https://github.com/sebastian-shirazi",
    },
    {
      title: "3D Gen AI Modeling with Unity",
      description: "Unity Pipeline for generating 3D models using AI, with focus on assessing accuracy of models generated by GPT-4o.",
      tags: ["C#", "Unity", "GPT-4o"],
      github: "https://github.com/sebastian-shirazi/LLMR-Research-S25",
    },
    {
      title: "Pagetable Implementation",
      description: "Simulates a multi-level page-table that stores mappings between physical and virtual addresses written in C.",
      tags: ["C", "Systems Programming"],
      github: "https://github.com/sebastian-shirazi/pagetables",
    },
  ];

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
        }
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, []);

  return (
    <section id="projects" className="py-32 px-6 lg:px-8" ref={sectionRef}>
      <div className="max-w-6xl mx-auto">
        <h2
          className={`text-sm uppercase tracking-wider text-muted-foreground mb-16 transition-all duration-700 text-center md:text-left ${
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'
          }`}
        >
          Selected Work
        </h2>

        <div className="grid md:grid-cols-2 gap-8">
          {projects.map((project, index) => (
            <a
              key={index}
              href={project.github}
              target="_blank"
              rel="noopener noreferrer"
              className={`group cursor-pointer transition-all duration-700 text-center md:text-left ${
                isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'
              }`}
              style={{ transitionDelay: `${(index + 1) * 100}ms` }}
            >
              <div className="relative overflow-hidden rounded-lg mb-4 bg-muted aspect-[3/2] transition-transform duration-500 group-hover:scale-[1.02]">
                {/* Blank background for now */}
              </div>
              <h3 className="text-xl font-semibold mb-2">{project.title}</h3>
              <p className="text-sm text-muted-foreground mb-3">
                {project.description}
              </p>
              <div className="flex flex-wrap gap-2 justify-center md:justify-start">
                {project.tags.map((tag) => (
                  <span key={tag} className="text-xs px-3 py-1 bg-muted text-muted-foreground rounded-full">
                    {tag}
                  </span>
                ))}
              </div>
            </a>
          ))}
        </div>
      </div>
    </section>
  );
}

export default Projects;
