import React from 'react';
import './Projects.css';

const Projects = () => {
  const projects = [
    {
        title: "AI Powered Risk Assessment Tool",
        description: "Uses AI to analyze video footage of basketball players to assess their risk of injury based on their movement patterns, considering factors such as fatigue, differentiation from proper form, and position of key joints.",
        technologies: ["Python", "mediapipe", "numpy", "pandas", "opencv-python"],
        image: "⛹️‍♂️",
        github: "https://github.com/sebastian-shirazi/AI-Driven-Risk-Assessment-for-Basketball",
        featured: true
    },
    {
      title: "Event Management App",
      description: "Full stack web application for managing events, with functionality for loggin in via Google OAuth, creating events, RSVPing to events, leaving messages on events, and attaching files to evevnts. Admin accounts can also be created and have elavated functionality.",
      technologies: ["Python", "CSS", "HTML", "Bootstrap", "Django", "SQLite", "AWS S3", "Heroku", "Google OAuth"],
      image: "🗓️",
      github: "https://github.com/sebastian-shirazi",
      featured: true
    },
    {
        title: "3D Gen AI Modeling with Unity",
        description: "Unity Pipeline for generating 3D models using AI, with focus on assessing accuracy of models generated by GPT-4o.",
        technologies: ["C#", "Unity", "GPT-4o", "DALL-E"],
        image: "🕹️",
        github: "https://github.com/sebastian-shirazi/LLMR-Research-S25",
        featured: false
      },
    {
      title: "Portfolio Website",
      description: "A modern, responsive portfolio website built with React, styled with CSS, and hosted on GitHub Pages. Features smooth animations and interactive elements.",
      technologies: ["React", "CSS", "JavaScript", "GitHub Pages"],
      image: "💼",
      github: "https://github.com/sebastian-shirazi/sebastian-shirazi.github.io",
      featured: false
    },
    {
      title: "Pagetable Implementation",
      description: "Simulates a multi-level page-table that stores mappings between physical and virtual addresses written in C.",
      technologies: ["C", "SSH", "VSCode", "Makefile"],
      image: "📖",
      github: "https://github.com/sebastian-shirazi/pagetables",
      featured: false
    },
  ];

  return (
    <section id="projects" className="projects">
      <div className="container">
        <div className="section-header">
          <h2 className="section-title">Featured Projects</h2>
          <p className="section-subtitle">Some of my recent work</p>
        </div>
        
        <div className="projects-grid">
          {projects.map((project, index) => (
            <div key={index} className={`project-card ${project.featured ? 'featured' : ''}`}>
              <div className="project-image">
                <span className="project-icon">{project.image}</span>
              </div>
              
              <div className="project-content">
                <h3 className="project-title">{project.title}</h3>
                <p className="project-description">{project.description}</p>
                
                <div className="project-spacer"></div>
                
                <div className="project-technologies">
                  {project.technologies.map((tech, techIndex) => (
                    <span key={techIndex} className="tech-tag">{tech}</span>
                  ))}
                </div>
                
                <div className="project-links">
                  <a href={project.github} className="project-link github">
                    <svg className="github-icon" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                    </svg>
                    GitHub
                  </a>
                </div>
              </div>
              
              {project.featured && (
                <div className="featured-badge">
                  <span>⭐ Featured</span>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Projects;